name = "..."
main = "src/api/index.ts"
compatibility_date = "2023-05-25"

[[r2_buckets]]
binding = "r2CMS"
bucket_name = "..."
preview_bucket_name = "..."

[[kv_namespaces]]
binding = "kvCMS"
id = "..."
preview_id = "..."