name = "cms"
main = "src/api/index.ts"
compatibility_date = "2023-05-25"

[[r2_buckets]]
binding = "r2CMS"
bucket_name = "..."
preview_bucket_name = "..."

[[d1_databases]]
binding = "d1CMS"
database_name = "..."
database_id = "..."
preview_database_id = "..."