-- Migration number: 0003 	 2022-12-17T14:03:48.363Z

-- SQLite

CREATE TABLE media (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  alt_text TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size INTEGER NOT NULL,
  path TEXT NOT NULL,
  user_id TEXT NOT NULL,
  created_at DATETIME NOT NULL CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL CURRENT_TIMESTAMP
);